### ISSUE TITLE
Failed to start game with error

### ISSUE THREAD

**Issue by Shroototem** [comp500/Jumploader#10]
Error:

java.lang.RuntimeException: java.lang.IllegalAccessException: class com.google.common.jimfs.SystemJimfsFileSystemProvider cannot access a member of class com.google.common.jimfs.JimfsFileSystem with modifiers "public"

Minecraft 1.16.2
Forge 33.0.20
Fabric Loader 0.9.2+build.206

Java jdk-11.0.8
OS Windows 10 Pro

**Comment by comp500** [comment]
Could you send a full log? Which launcher are you using, and are you using a non-standard JDK distribution? (e.g. OpenJ9/Zulu instead of Hotspot)

**Comment by Shroototem** [comment]
I'm using the MultiMc Launcher with a Hotspot JDK.
[latest.log](https://github.com/comp500/Jumploader/files/5119500/latest.log)

**Comment by Shroototem** [comment]
It seems that I'm an idiot and didn't read the description correctly... I had Fabric enabled before starting the game. Sorry for the nonsense.

**Comment by comp500** [comment]
Ah, no worries. Do note that if modpacks include Jumploader you can just remove it (and Forge) and install Fabric anyway.
