### ISSUE TITLE
Possibly not loading the newest version of Fabric?

### ISSUE THREAD

**Issue by MechanosG** [comp500/Jumploader#13]
Short version, the mod [Automated Crafting](https://www.curseforge.com/minecraft/mc-mods/automated-crafting#c38) put out an update that started preventing my game from loading, with this error:
> [20:11:25] [main/FATAL]: A critical error occurred
> net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: automated_crafting requires {fabricloader @ [>=0.10.6+build.214]}

But the previous version of that mod didn't do it.  So I reported it to the author.  He was unable to reproduce the error, and wanted me to make sure I was loading the right version of fabric.  However, I'm using Jumploader, so the latest version "should" be loading.  The console readout only mentions 0.10.5+build.213.  So I manually installed the latest fabric to the install folder, which created the proper 0.10.6+build.214 folder, then I deleted the 0.10.5+build.213 folder.  But Jumploader restored the old version and seems to be ignoring the newer install.

How do I get Jumploader to load the latest fabric instead?  :)
MC 1.16.3

_Edited for typos_

**Comment by comp500** [comment]
The `.jumploader` folder caches the latest Fabric loader version the first time you run the game, so you'll want to delete that folder to get it to download the latest version. I'm also releasing a new version today that should let you configure it in the config.

**Comment by MechanosG** [comment]
Awesome.  Deleting the .jumploader folder fixed the issue.  Didn't even have to remove 0.10.5+build.213.  Thanks!
