### ISSUE TITLE
Failed to download jar: Authentication token is invalid, please go online to download the Minecraft JAR!

### ISSUE THREAD

**Issue by luciobortoletto** [comp500/Jumploader#14]
When I start my Forge server with Jumploader to run Fabric, it crashes with the error "Failed to download jar: Authentication token is invalid, please go online to download the Minecraft JAR!".
The log is attached.
[latest.log](https://github.com/comp500/Jumploader/files/5726081/latest.log)

I need help as fast as possible, because my friends are waiting for me :(

**Comment by comp500** [comment]
You probably want to run Fabric directly with https://fabricmc.net/use/?page=server - note that Jumploader doesn't make Forge and Fabric run together, only Fabric mods will work. This is really easy to fix though, I'll push a fix now.

**Comment by luciobortoletto** [comment]
> note that Jumploader doesn't make Forge and Fabric run together, only Fabric mods will work.
I know

> This is really easy to fix though, I'll push a fix now.
OK. thank you!

**Comment by kabadesu** [comment]
Aof3 is getting reports of this error occurring with AOF3 2.5.9 through curseforge launcher. We'd normally recommend people use either GDlauncher or multimc to run the pack. It's not happening too often but I'm wondering if you might know the cause of it? Or how to kind of refresh the token? (Sorry a bit out of my depth)

**Comment by luciobortoletto** [comment]
> Aof3 is getting reports of this error occurring with AOF3 2.5.9 through curseforge launcher. We'd normally recommend people use either GDlauncher or multimc to run the pack. It's not happening too often but I'm wondering if you might know the cause of it? Or how to kind of refresh the token? (Sorry a bit out of my depth)

Sorry, I'm not an expert and I can't help you
