### ISSUE TITLE
Requires Fabric Loader 0.11.0

### ISSUE THREAD

**Issue by PalgamingHD** [comp500/Jumploader#20]
Many of my mods complain and crash that the Fabric Loader is not on 0.11.0, fabric API is up to date and the mods are working using a normal fabric setup, but not with jumploader. Any fixes that don't include changing the mod's requirements?

**Comment by comp500** [comment]
In the jumploader.json config file you can edit `pinFabricLoaderVersion` to the version you want, or delete the file and it should grab the latest version.

**Comment by PalgamingHD** [comment]
It is on 0.11.3, and actually minecraft launches normally but the error still shows on multiple mods. I don't know if I should contact the individual authors but there's no fabric loader error on a normal setup.

**Comment by PalgamingHD** [comment]
Never mind, just needed me to create a new profile.
