### ISSUE TITLE
jumploader v2.1.3: java.lang.NullpointerException crash 

### ISSUE THREAD

**Issue by farwedyed** [comp500/Jumploader#22]
https://pastebin.ubuntu.com/p/Z3ZNQWD5WC/
that is the crash report and im using 1.16.5 2.1.3

**Comment by comp500** [comment]
Could you add https://www.curseforge.com/minecraft/mc-mods/mixintrace to the mods folder and try again? That should give more information in the crash log.

**Comment by farwedyed** [comment]
> Could you add https://www.curseforge.com/minecraft/mc-mods/mixintrace to the mods folder and try again? That should give more information in the crash log.

https://pastebin.ubuntu.com/p/ZFxXTk6trt/
here

**Comment by farwedyed** [comment]
@comp500 
https://pastebin.ubuntu.com/p/ZFxXTk6trt/ i added on it that mixintrace mod and thats the crash log so??

**Comment by comp500** [comment]
Please wait, I haven't had the chance to look into the issue yet.

**Comment by farwedyed** [comment]
> se wait, I haven't had the chance to look into the issue yet.

@comp500 so i need to wait right?

**Comment by farwedyed** [comment]
@comp500 are you going to solve my proplem or what its been 4 days ;c

**Comment by comp500** [comment]
This looks like an issue with Dark Loading Screen, not Jumploader. Please test without Jumploader, and if the issue still occurs report it to the author of Dark Loading Screen instead.
