### ISSUE TITLE
not able to create a 1.18 snapshot instance

### ISSUE THREAD

**Issue by MSandro** [comp500/Jumploader#23]
Hello, I am trying to create a 1.18 snapshot release, but Jumploader seems to not work for 1.17.1.

**Comment by MSandro** [comment]
Aufgrund der Fabric-Implementierung in CurseForge hat Jumploader keinen wirklichen Nutzen mehr. Aber wenn es möglich wäre, Snapshot-Versionen zu starten, wäre es immer noch nützlich.

**Comment by comp500** [comment]
I probably won't maintain this mod any more as CurseForge now supports Fabric natively. For snapshot support I'd suggest asking them directly.
