### ISSUE TITLE
Crash with Jumploader, Fabric Rendering (v1) and Patchouli

### ISSUE THREAD

**Issue by QuasiCastle7479** [comp500/Jumploader#3]
https://gist.githubusercontent.com/Cloak-Bot/e38e14595600ca0b605ade208037b8d1/raw/f8f7fd916f010408eeb4cd0a9c82729e9d7fd876/crash.txt

**Comment by comp500** [comment]
Can you reproduce the crash without Jumploader?

**Comment by QuasiCastle7479** [comment]
There's an additional problem which has the effect of me not even being able to start the game. I'm trying to fix that. However, there were two other mods that crashed the game as well, so I think it would crash without Jumploader as well.

**Comment by QuasiCastle7479** [comment]
After loading the game and moving Jumploader out of the mods folder, it still crashes:
https://gist.githubusercontent.com/Cloak-Bot/2881fe2a230373cac25fb5a82bd5862a/raw/3dd6b20d56ed4e6bb694dc840542e946e7998333/crash.txt

**Comment by comp500** [comment]
It's likely to be a bug in Patchouli (or other mods) then, not Jumploader

**Comment by QuasiCastle7479** [comment]
It might, but it still throws up Jumploader as a cause for the crash. I might not have moved it properly, but I wouldn't know how to do it otherwise.

**Comment by comp500** [comment]
Not Enough Crashes will do that because Jumploader is in the stack trace. I can't really do much about this in Jumploader, you could ask Not Enough Crashes to exclude Jumploader somehow?

**Comment by QuasiCastle7479** [comment]
Would you know how to do that?

**Comment by comp500** [comment]
By "asking Not Enough Crashes" I mean asking the developers, e.g. reporting it as an issue on [their issue tracker](https://github.com/natanfudge/Not-Enough-Crashes/issues).

**Comment by QuasiCastle7479** [comment]
Ah, I'll try it in any case, thanks!

**Comment by comp500** [comment]
What launcher are you using?

**Comment by QuasiCastle7479** [comment]
I'm using the 1.6.93 launcher via Twitch. I'll try the Fabric launcher to see if it works

**Comment by comp500** [comment]
MultiMC should work, or you can use the vanilla launcher - see [https://fabricmc.net/use/](https://fabricmc.net/use/)

**Comment by QuasiCastle7479** [comment]
How does that one work? I've downloaded the jar-file but can't seem to find the API's and open the jar-file

**Comment by comp500** [comment]
There's a guide at [https://fabricmc.net/wiki/install](https://fabricmc.net/wiki/install). I recommend MultiMC, as it's easier to use. You should then be able to open your instance folder in Twitch (Cog icon -> Open Folder) then copy the mods from there into your MultiMC instance (by clicking Minecraft Folder below the launch button).

**Comment by QuasiCastle7479** [comment]
Thanks, I'll follow your advice!
