### ISSUE TITLE
Datapack loading bug

### ISSUE THREAD

**Issue by Wtoll** [comp500/Jumploader#5]
Hey, the other day I was a called into voice to troubleshoot a bug with Terrestria and Cinderscapes that meant leaves were rapidly decaying from trees. I believe we determined that the issue was with jumploader not properly loading the logs tag and it getting corrupted somewhere in the loading process. I’m opening this issue both to reference in other issues we’ve been getting on our mods, and to point people in the right place, but also to get an update on the status of this issue, and whether or not we have an idea of how to fix it.

**Comment by comp500** [comment]
Ah yes, sorry for not keeping you updated on this. I've been rewriting Jumploader to fix specifically this problem, and the new launching system seems to work much better than before. I'm now working on updating the configuration/dependency resolution system to grab the libraries correctly.

**Comment by comp500** [comment]
Fixed in version 2.0.0
